export const fieldIDs = [
    "movie-title",
    "movie-duration",
    "movie-genre",
    "movie-writer",
    "movie-director",
    "movie-producer",
    "movie-animator",
    "movie-cast",
    "movie-logline",
    "movie-target",
    "movie-synopsis",
    "movie-director-statement",
    "movie-producer-vision",
    "movie-other-resource",
    "movie-crew-milestone",
    "movie-director-portfolio-link",
    "movie-producer-portfolio-link",
    "upload-form-akta-pendirian-file",
    "upload-form-akta-perubahan-sk-kemenkuham-file",
    "upload-form-id-number-file",
    "upload-form-nomor-induk-file",
    "upload-form-npwp-file",
    "upload-form-tax-file",
    "upload-form-card-number-file",
    "upload-form-profile-and-portfolio-file",
    "upload-form-lampiran-1",
    "upload-form-lampiran-2",
    "upload-form-lampiran-3",
    "upload-form-lampiran-4",
    "upload-form-lampiran-5",
    "upload-form-lampiran-6",
    "upload-form-lampiran-7",
    "full-name",
    "id-number",
    "company-name",
    "email",
    "whatsapp-number",
    "movie-category",
    "movie-crew",
    "upload-form-sk-kemenkumham-sk-kemenkumham",
    "upload-form-sk-kemenkumham-sk-kemenkumham-perubahan"
]

export const fieldIDsName = {
    "movie-title": "JUDUL FILM",
    "movie-duration": "DURASI FILM",
    "movie-genre": "GENRE",
    "movie-writer": "NAMA PENULIS SKENARIO",
    "movie-director": "NAMA SUTRADARA",
    "movie-producer": "NAMA PRODUSER",
    "movie-animator": "NAMA ANIMATOR",
    "movie-cast": "DAFTAR NAMA PEMAIN (RENCANA)",
    "movie-logline": "LOGLINE (3 KALIMAT)",
    "movie-target": "ULASAN TARGET PENONTON (MAKSIMAL 400 KATA)",
    "movie-synopsis": "SINOPSIS (200-400 KATA)",
    "movie-director-statement": "DIRECTOR'S STATEMENT (200-400 KATA)",
    "movie-producer-vision": "VISI PRODUSER (200-400 KATA)",
    "movie-other-resource": "RENCANA PENDANAAN PRODUKSI FILM",
    "movie-crew-milestone": "RENCANA DISTRIBUSI ATAU PENAYANGAN FILM",
    "movie-director-portfolio-link": "TAUTAN DARING DARI CONTOH HASIL KARYA (PORTOFOLIO) SUTRADARA",
    "movie-producer-portfolio-link": "TAUTAN DARING DARI CONTOH HASIL KARYA (PORTOFOLIO) PRODUSER",
    "upload-form-akta-pendirian-file": "UNGGAH AKTA PENDIRIAN DAN SK KEMENKUMHAM (MINIMAL BERDIRI SEJAK 1 JANUARI 2019)",
    "upload-form-akta-perubahan-sk-kemenkuham-file": "UNGGAH AKTA PERUBAHAN DAN SK KEMENKUMHAM (TERKAIT SUSUNAN KEPENGURUSAN YANG BERLAKU APABILA ADA PERUBAHAN DARI AKTA PENDIRIAN)",
    "upload-form-id-number-file": "UNGGAH SALINAN KTP PENANGGUNG JAWAB / DIREKTUR PH",
    "upload-form-nomor-induk-file": "UNGGAH NOMOR INDUK BERUSAHA (NIB) DENGAN NOMOR KBLI 74141 (AKTIVITAS DESAIN KHUSUS YAKNI FILM, VIDEO, PROGRAM TV, ANIMASI DAN KOMIK)",
    "upload-form-npwp-file": "UNGGAH DOKUMEN NOMOR POKOK WAJIB PAJAK ATAS NAMA BADAN USAHA",
    "upload-form-tax-file": "UNGGAH SURAT PEMBERITAHUAN TAHUNAN (SPT) PAJAK 1 TAHUN TERAKHIR",
    "upload-form-card-number-file": "UNGGAH DOKUMEN REKENING ATAS NAMA BADAN USAHA",
    "upload-form-profile-and-portfolio-file": "UNGAH PROFIL DAN PORTOFOLIO BADAN USAHA RUMAH PRODUKSI",
    "upload-form-lampiran-1": "LAMPIRAN 1",
    "upload-form-lampiran-2": "LAMPIRAN 2",
    "upload-form-lampiran-3": "LAMPIRAN 3",
    "upload-form-lampiran-4": "LAMPIRAN 4",
    "upload-form-lampiran-5": "LAMPIRAN 5",
    "upload-form-lampiran-6": "LAMPIRAN 6",
    "upload-form-lampiran-7": "LAMPIRAN 7",
    "full-name": "NAMA LENGKAP",
    "id-number": "NOMOR IDENTITAS/NIK/PASPOR",
    "company-name": "NAMA RUMAH PRODUKSI",
    "email": "ALAMAT EMAIL",
    "whatsapp-number": "NOMOR WHATSAPP",
    "movie-category": "KATEGORI FILM",
    "movie-crew": "ESTIMASI TOTAL TENAGA KERJA YANG TERLIBAT (PEMERAN DAN KRU)",
    "upload-form-sk-kemenkumham-sk-kemenkumham": "UNGGAH SK KEMENKUMHAM AKTA PENDIRIAN",
    "upload-form-sk-kemenkumham-sk-kemenkumham-perubahan": "UNGGAH SK KEMENKUMHAM AKTA PERUBAHAN"
}
